### ISSUE TITLE
Issue: Editor support missing

### ISSUE THREAD

**Issue by 0Cue** [migteam/better-trello-browser-extension#4]
This extension has been a lifesaver, but it appears to have ceased functioning as of today.
Any attempt to open a card while using the Legacy Editor will simply spit out the following error:
![image](https://github.com/user-attachments/assets/67a0c0a0-76a2-4c73-9108-dfbd6d9099c1)

Following this, any attempt to edit the card will simply return the user to the default WYSIWYG editor.

I don't believe this issue has been caused by my own error, and appears to remain consistent across several devices and several accounts. I am unsure if this issue is otherwise widespread. Issue persists upon both re-install and restart.

I also apologise if this report is missing common report etiquette in any way. Thank you for all your great work!

**Comment by sewerynkalemba** [comment]
Hello @0Cue,

So with the new card back enhancements Trello is introducing they've changed the way editor is rendered and my hack to bring markdown editor is no longer working. 

For now, you can switch the new feature off in https://trello.com/labs. It should be labeled as Card back enhancements. In the meantime, I'm working on getting markdown editor back even with these changes applied.

<img width="636" alt="image" src="https://github.com/user-attachments/assets/37702856-704d-4e66-9f40-a2bf98967fd4">

Thank you for the support :)

**Comment by sewerynkalemba** [comment]
I did my best to bring markdown editor back to Trello with the new changes. Although I couldn't make mentions work :(

I just released new version (https://github.com/migteam/better-trello-browser-extension/releases/tag/1.4), and it should be available in browser extension hubs soon.

**Comment by 0Cue** [comment]
Just installed 1.4, can confirm it's working perfectly. Great work as always, thank you!
![image](https://github.com/user-attachments/assets/cf252c5d-c82a-4d75-b10e-4a2a50949a71)

**Comment by sewerynkalemba** [comment]
@0Cue Great to hear that! Thanks!
