### ISSUE TITLE
Weird Scroll Issue

### ISSUE THREAD

**Issue by Rift0715** [migteam/better-trello-browser-extension#6]
![image](https://github.com/user-attachments/assets/31bd181f-1938-4682-bed4-eafc60035c27)
no matter how "long" the description of a card is using Legacy Editor, it doesn't actually extend the box. It remains at like, three-ish lines long. It is incredibly irritating. Not sure if there's a fix.

**Comment by sewerynkalemba** [comment]
Hi @Rift0715,

can you confirm that you use the latest version of the extension (1.7)?

**Comment by Rift0715** [comment]
yes. i am @sewerynkalemba 
![image](https://github.com/user-attachments/assets/59993a85-4b07-4b75-b6ea-252251355891)

**Comment by sewerynkalemba** [comment]
@Rift0715,

Do you use Firefox or Chromium-based browser?

**Comment by Rift0715** [comment]
i use Firefox, yes

**Comment by sewerynkalemba** [comment]
Ok, I've used a CSS property `field-sizing` that is not supported by Firefox – that's my oversight. I will try to find a workaround and realease a new version with the fix as soon as possible. Sorry for the inconvenience.

**Comment by sewerynkalemba** [comment]
@Rift0715,

The fix was published with version 1.8, which should be already available to update to on Firefox. It's not as smooth as it can be, but I believe it's enough of a workaround until we get `field-sizing` property in Firefox.
